name: "Code Coverage"

on:
  push:
    # The branches below must be a subset of the branches above
    branches: [ 'prcoverage' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}